spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academy
    username: best_user
    password: best_user
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none
